name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    name: CI (vitest ${{ matrix.vitest }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vitest: [3, 4]
    env:
      NX_CLOUD_ENABLED: "false"
    # NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun run ci
      - name: Set Vitest version
        run: bun add -D vitest@^${{ matrix.vitest }} @vitest/coverage-v8@^${{ matrix.vitest }}
      - run: bun run nx lint
      - run: bun run nx test
      - run: bun run nx build
